import type { PlatformMeta } from "./types";

/** خيارات مجال المحتوى (النيش) الخاصة بيوتيوب - تؤثر مباشرة على معدل الـ RPM */
export const YOUTUBE_NICHE_OPTIONS = [
  { value: "finance", label: "مال، استثمار وأعمال" },
  { value: "tech", label: "تقنية وبرمجة" },
  { value: "education", label: "تعليم وتطوير ذات" },
  { value: "gaming", label: "ألعاب" },
  { value: "entertainment", label: "ترفيه ومنوعات" },
  { value: "beauty", label: "جمال وموضة" },
  { value: "lifestyle", label: "لايف ستايل وفلوقز" },
  { value: "food", label: "طبخ وطعام" },
  { value: "fitness", label: "لياقة وصحة" },
  { value: "travel", label: "سفر وسياحة" },
  { value: "news", label: "أخبار ومجتمع" },
  { value: "other", label: "مجال آخر" },
];

export const PLATFORMS: Record<string, PlatformMeta> = {
  youtube: {
    id: "youtube",
    name: "يوتيوب",
    tagline: "أرباح الإعلانات + الرعايات",
    brandColor: "#FF0000",
    fields: [
      {
        name: "subscribers",
        label: "عدد المشتركين",
        type: "number",
        placeholder: "مثال: 25000",
        unit: "مشترك",
        min: 0,
      },
      {
        name: "avgViews30d",
        label: "متوسط مشاهدات الفيديو (آخر 30 يوم)",
        type: "number",
        placeholder: "مثال: 8000",
        unit: "مشاهدة",
        min: 0,
      },
      {
        name: "videosPerMonth",
        label: "عدد الفيديوهات المنشورة شهرياً",
        type: "number",
        placeholder: "مثال: 8",
        unit: "فيديو",
        min: 0,
        max: 200,
      },
      {
        name: "niche",
        label: "نوع المحتوى (النيش)",
        type: "select",
        helperText: "النيش بيأثر بشكل مباشر في قيمة الإعلانات (RPM)",
        options: YOUTUBE_NICHE_OPTIONS,
      },
    ],
  },
  instagram: {
    id: "instagram",
    name: "إنستجرام",
    tagline: "شراكات ومنشورات ممولة",
    brandColor: "#E1306C",
    fields: [
      {
        name: "followers",
        label: "عدد المتابعين",
        type: "number",
        placeholder: "مثال: 40000",
        unit: "متابع",
        min: 0,
      },
      {
        name: "avgLikes",
        label: "متوسط اللايكات في المنشور",
        type: "number",
        placeholder: "مثال: 1500",
        unit: "لايك",
        min: 0,
      },
      {
        name: "avgComments",
        label: "متوسط الكومنتات في المنشور",
        type: "number",
        placeholder: "مثال: 80",
        unit: "كومنت",
        min: 0,
      },
      {
        name: "avgReach",
        label: "متوسط الريتش (الوصول)",
        type: "number",
        placeholder: "مثال: 25000",
        unit: "حساب",
        min: 0,
      },
    ],
  },
  tiktok: {
    id: "tiktok",
    name: "تيك توك",
    tagline: "Creator Rewards + رعايات",
    brandColor: "#000000",
    fields: [
      {
        name: "followers",
        label: "عدد المتابعين",
        type: "number",
        placeholder: "مثال: 60000",
        unit: "متابع",
        min: 0,
      },
      {
        name: "avgViews",
        label: "متوسط مشاهدات الفيديو",
        type: "number",
        placeholder: "مثال: 30000",
        unit: "مشاهدة",
        min: 0,
      },
      {
        name: "avgLikes",
        label: "متوسط اللايكات في الفيديو",
        type: "number",
        placeholder: "مثال: 2500",
        unit: "لايك",
        min: 0,
      },
      {
        name: "videosPerMonth",
        label: "عدد الفيديوهات المنشورة شهرياً",
        type: "number",
        placeholder: "مثال: 20",
        unit: "فيديو",
        min: 0,
        max: 300,
      },
    ],
  },
  facebook: {
    id: "facebook",
    name: "فيسبوك",
    tagline: "إعلانات الفيديو + رعايات",
    brandColor: "#1877F2",
    fields: [
      {
        name: "followers",
        label: "عدد المتابعين للصفحة",
        type: "number",
        placeholder: "مثال: 100000",
        unit: "متابع",
        min: 0,
      },
      {
        name: "avgViews",
        label: "متوسط مشاهدات الفيديو",
        type: "number",
        placeholder: "مثال: 15000",
        unit: "مشاهدة",
        min: 0,
      },
      {
        name: "avgEngagement",
        label: "متوسط التفاعل (لايك + كومنت + مشاركة)",
        type: "number",
        placeholder: "مثال: 900",
        unit: "تفاعل",
        min: 0,
      },
      {
        name: "postsPerMonth",
        label: "عدد المنشورات/الفيديوهات شهرياً",
        type: "number",
        placeholder: "مثال: 12",
        unit: "منشور",
        min: 0,
        max: 300,
      },
    ],
  },
  x: {
    id: "x",
    name: "إكس",
    tagline: "مشاركة أرباح الإعلانات + رعايات",
    brandColor: "#000000",
    fields: [
      {
        name: "followers",
        label: "عدد المتابعين",
        type: "number",
        placeholder: "مثال: 20000",
        unit: "متابع",
        min: 0,
      },
      {
        name: "avgImpressions",
        label: "متوسط المشاهدات (Impressions) للمنشور",
        type: "number",
        placeholder: "مثال: 50000",
        unit: "مشاهدة",
        min: 0,
      },
      {
        name: "postsPerMonth",
        label: "عدد المنشورات شهرياً",
        type: "number",
        placeholder: "مثال: 60",
        unit: "منشور",
        min: 0,
        max: 1000,
      },
    ],
  },
};

export const PLATFORM_LIST: PlatformMeta[] = Object.values(PLATFORMS);
